# Site Info
title: xúnyì’s 
tagline: 'just for you'
description: 'want to do something'
url: http://xiangblq.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/foryou/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author: 
  name: xúnyì
  description: <strong>三嵗</strong> 性格卑劣，是个好人
  gravatar:  # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/gichanglee/
    github:    https://github.com/ratsgo
    facebook:  https://www.facebook.com/gichanglee.84
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:gichang_lee@korea.ac.kr

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/foryou/'
    - { Categories: '/foryou/categories/' }
    - { Tags: '/foryou/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/foryou/tags/'
category_page: '/foryou/categories/'

hero:
  image: https://xiangblq.github.io/public/img/picture.jpg
  caption: Original Artwork &copy; Pablo Picasso. Girl before a Mirror. Boisgeloup, March 1932. Oil on canvas

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-93172815-1' # leave blank if you don't want google analytics
disqus_short_name: 'ratsgo-github-io' # leave blank if you don't want disqus

