# Site Info
title: xúnyì’s 
tagline: ''
description: 'want to do something'
url: http://xiangblq.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/foryou/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author: 
  name: xúnyì
  description: <strong>三嵗</strong> 性格卑劣，是个好人
  gravatar:  # md5 hash of your email address
  contact:
    book:  https://xiangblq.github.io/
    image:  https://xiangblq.github.io/
    archive:  https://xiangblq.github.io/
    commenting:  https://support.qq.com/products/315295?
    globe:  http://timelineofearth.com/
    rmb:  https://s2.ax1x.com/2019/10/29/KRZsXT.png
    qq:  tencent://message/?uin=928388405&Site=Senlon.Net&Menu=yes
    #facebook:  <hide>
    #weibo:    <hide>
    email:     mailto:chare405@foxmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/foryou/'
    - { Categories: '/foryou/categories/' }
    - { Tags: '/foryou/tags/' }
  Friend: 
    - '/Friend/'
  About:          
    - '/about/'
  Colophon: 
    - '/colophon/'

# Where are tags and categories displayed
tag_page: '/foryou/tags/'
category_page: '/foryou/categories/'

hero:
  image: https://xiangblq.github.io/public/img/picture.png
  caption: 千里江山，家国所在；青山云雨，故人相怀

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'G-THGWTXXRBG' # leave blank if you don't want google analytics
disqus_short_name: 'xunyi' # leave blank if you don't want disqus

